In [3]:
import numpy as np

In [5]:
a= np.array([1,2,3])

In [6]:
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [7]:
a.ndim

1

In [9]:
b =np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b.ndim

2

In [14]:
print('Shape of B is',b.shape) #rows and column
print('Size of B is ',b.size)
print('datatype of value in B is',b.dtype)

Shape of B is (2, 3)
Size of B is  6
datatype of value in B is int32


In [16]:
print(a[0],a[1],a[2])

1 2 3


In [35]:
name= ['a','b','c','d']
age=[10,20,30,40]
salary=[10,20.5,30.6,40.8]

In [36]:
table = np.zeros(4,dtype={'names':('name','age','salary'),
                'formats':('U2','i2','f8')})

print(table.dtype)

[('name', '<U2'), ('age', '<i2'), ('salary', '<f8')]


In [39]:
table['name']=name
table['age']=age
table['salary']=salary
print(table)

[('a', 10, 10. ) ('b', 20, 20.5) ('c', 30, 30.6) ('d', 40, 40.8)]


In [41]:
table.ndim

1

In [42]:
table[1]

('b', 20, 20.5)

In [45]:
print(table[table['age']>15]['salary'])

[20.5 30.6 40.8]


In [48]:
a =np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
b=np.ones_like(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
f= np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [66]:
np.random.seed(1)

f= np.random.random((3,3))
print(f)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


In [87]:
f= np.random.randint(1,10,(3,3))
print(f)

[[1 4 4]
 [9 4 6]
 [7 8 6]]


In [89]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [153]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [154]:
x =np.array([[1,2,3],[4,5,6]])
y =np.array([[7,8,9],[10,11,12]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [159]:
print('multiplication of x and y is \n',x*y)
print('addition of x and y is \n',x+y)
print('sunstraction of x and y is \n',x-y)
print('division of x and y is \n',x/y)
print('sqaure of x and y is \n',x*x)
print('exponential of x is \n',np.exp(x))
print('x poer 3 is \n',np.power(x,3))


multiplication of x and y is 
 [[ 7 16 27]
 [40 55 72]]
addition of x and y is 
 [[ 8 10 12]
 [14 16 18]]
sunstraction of x and y is 
 [[-6 -6 -6]
 [-6 -6 -6]]
division of x and y is 
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
sqaure of x and y is 
 [[ 1  4  9]
 [16 25 36]]
exponential of x is 
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
x poer 3 is 
 [[  1   8  27]
 [ 64 125 216]]


In [160]:
print('log of x is \n',np.log(x))
print('\nlog of x with base of 10 is \n',np.log10(x))
print('\nlog of x with base of 2 is \n',np.log2(x))



log of x is 
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]

log of x with base of 10 is 
 [[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]

log of x with base of 2 is 
 [[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]


In [ ]:
#Vector Operation- linear algebra

In [1]:
import numpy as np

In [3]:
vec = np.arange(0,5)
print(vec)

[0 1 2 3 4]


In [5]:
print( vec *2)

[0 2 4 6 8]


In [7]:
print( vec /2)
print( vec **2)
print( vec +2)

[0.  0.5 1.  1.5 2. ]
[ 0  1  4  9 16]
[2 3 4 5 6]


In [8]:
#Matrix - linear Algebra

In [11]:
a = np.array([np.linspace(1,3,3),np.linspace(4,6,3),np.linspace(7,9,3)])
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [12]:
a1 = np.array([np.linspace(11,13,3),np.linspace(14,16,3),np.linspace(17,19,3)])
print(a1)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


In [13]:
type(a1)

numpy.ndarray

In [16]:
print(a.T)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [22]:
amat = np.matrix(a)
print(amat)
print('\n',type(amat))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

 <class 'numpy.matrix'>


In [23]:
a1mat = np.matrix(a1)
print(a1mat)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


In [24]:
amat*a1mat

matrix([[ 90.,  96., 102.],
        [216., 231., 246.],
        [342., 366., 390.]])

In [25]:
amat.shape

(3, 3)

In [26]:
amat.sum()

45.0

In [27]:
amat.sum(axis =0) # 0 for column and  for rows

matrix([[12., 15., 18.]])

In [28]:
print('matrix Average is',amat.sum())
print('matrix Average Across coln are are \n',amat.sum(axis=0))
print('matrix Average Across rows are \n',amat.sum(axis=1))

matrix Average is 45.0
matrix Average Across coln are are 
 [[12. 15. 18.]]
matrix Average Across rows are 
 [[ 6.]
 [15.]
 [24.]]


In [29]:
print('matrix vriance is',amat.var())
print('matrix vriance Across coln are are \n',amat.var(axis=0))
print('matrix vriance Across rows are \n',amat.var(axis=1))

matrix Average is 6.666666666666667
matrix Average Across coln are are 
 [[6. 6. 6.]]
matrix Average Across rows are 
 [[0.66666667]
 [0.66666667]
 [0.66666667]]


In [42]:
# Concatination and Stacking

a = np.array([[1,2],[3,4]])
print(a,"\n")
b = np.array([[5,6]]) 
print(b)

[[1 2]
 [3 4]] 

[[5 6]]


In [44]:
print(np.concatenate((a,b),axis = 0))

[[1 2]
 [3 4]
 [5 6]]


In [46]:
print(np.concatenate((a,b.T),axis = 1))

[[1 2 5]
 [3 4 6]]
